### ISSUE TITLE
Singleton

### ISSUE THREAD

**Issue by fdisotto** [itsgoingd/slim-facades#2]
Hi, how can I use singleton ($app->container->singleton) with facades?

**Comment by itsgoingd** [comment]
Hey, I've updated the readme with info about creating custom facades.

In your case, you wold register custom singleton via:

``` php
$app->container->singleton('my_singleton', function(){ return new MySingleton(); });
```

Then create a facade class for this component:

``` php
class MyFacade extends SlimFacades\Facade
{
    // return the name of the component from the DI container
    protected static function getFacadeAccessor() { return 'my_singleton'; }
}
```

**Comment by fdisotto** [comment]
Now I've understand how to use these facades :)
