### ISSUE TITLE
Route::resource

### ISSUE THREAD

**Issue by ikhsan017** [itsgoingd/slim-facades#5]
Hi,

Thanks for creating great package to simplify Slim usage :)

by the way, is there is any chance we can add Route::resource to the route facade?

regards

**Comment by itsgoingd** [comment]
Hey,

I would love to see this feature in Slim, using it in Laravel projects all the time. I'm not sure if this is the right place for it though, as the purpose of this library is to provide easier access to Slim's API, and I don't want to over bloat it with custom features.

I suggest making this feature request on the main Slim repo and we'll see how it goes. For now you can extend and customise the Route facade yourself.

Thanks!

**Comment by ikhsan017** [comment]
Thanks, 
will try to extends the route facade

btw, great package! :), and just ignore those facade name issue :D

regards
