### ISSUE TITLE
View::render and View::display not rendering variable

### ISSUE THREAD

**Issue by ikhsan017** [itsgoingd/slim-facades#6]
Hi,

I am trying to implement twig as slim view renderer,

when I am using Slim-facade to render a view, variable is not passed to the view

template.twig

``` html
hello {{ name }}!
```

the routes.php

``` php
View::display('template.twig', array('name' => 'John'));
//this only produce 'Hello !'

$app->render('template.twig', array('name' => 'John'));
//this produce 'Hello John!' perfectly
```

I am using this code to initiate Slim, slim-facades, and twig

``` php
require __DIR__.'/../../vendor/autoload.php';
use SlimFacades\Facade;
use Illuminate\Database\Capsule\Manager as Capsule;

/**
 * Initialize Slim application
 */

$app = new Slim\Slim(array(
    'view'              => new \Slim\Views\Twig(),
    'templates.path'    => __DIR__.'/../views'
));

$view = $app->view();
$view->parserOptions = array(
    'debug' => true,
    'cache' => __DIR__ . '/../storage/cache'
);

$view->parserExtensions = array(
    new \Slim\Views\TwigExtension(),
);

// initialize the Slim Facade class

Facade::setFacadeApplication($app);
Facade::registerAliases(array(
    'Model'     => 'Illuminate\Database\Eloquent\Model',
    'Sentry'    => 'Cartalyst\Sentry\Facades\Native\Sentry',
    'App'       => 'SlimFacades\App',
    'Config'    => 'SlimFacades\Config',
    'Input'     => 'SlimFacades\Input',
    'Log'       => 'SlimFacades\Log',
    'Request'   => 'SlimFacades\Request',
    'Response'  => 'SlimFacades\Response',
    'Route'     => 'SlimFacades\Route',
    'View'      => 'SlimFacades\View',
));

```

**Comment by prisis** [comment]
did you try View::render('template.twig', array('name' => 'John'));

**Comment by ikhsan017** [comment]
since View::render return the rendered view, I use echo here

``` php
echo View::render('template.twig', array('name' => 'John'));
```

but it give the same result, no variable passed

you can clone this repo to reproduce the issue
https://github.com/ikhsan017/SlimStarter

**_edit**_
since $app->render('template.twig', $data) works as expected

I am trying App::render('template.twig', $data) and it also workd

**Comment by itsgoingd** [comment]
Hey, this is actually an upstream bug in the Twig view, I've sent a pull request with a fix https://github.com/codeguy/Slim-Views/pull/21.

**Comment by ikhsan017** [comment]
Hi, I see your pull request was merged to upstream repo, but it is in develop branch.

until it merged to the master branch, I think I can go with `App::render()` instead of `View::display()`

edit
using `"slim-views" : "dev-develop"` to for a while till 0.1.2 released
